-- V1 — baseline do schema existente.
--
-- Gerado a partir das entidades JPA em dialeto PostgreSQL, refletindo exatamente
-- o que `ddl-auto: validate` espera encontrar. NÃO roda em bancos que já existem:
-- dev e produção são carimbados via `flyway.baseline-on-migrate`, que registra a
-- V1 como aplicada sem executá-la. Este script só chega a rodar em banco vazio.
--
-- A partir daqui, toda alteração de entidade exige um V2__, V3__… correspondente.
-- O Hibernate nunca mais altera schema: dev e prod usam `validate`.


    create table banks (
        code integer not null unique,
        id bigint generated by default as identity,
        synced_at timestamp(6) not null,
        ispb varchar(10),
        name varchar(120) not null,
        full_name varchar(200),
        primary key (id)
    );

    create table cmc_credit_usage (
        credits_used integer not null,
        reference_month varchar(7) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        primary key (id),
        constraint uk_cmc_credit_month unique (reference_month)
    );

    create table cmc_crypto_snapshots (
        circulating_supply numeric(30,4),
        cmc_id integer not null,
        cmc_rank integer,
        current_price numeric(30,10) not null,
        market_cap numeric(30,2),
        market_cap_dominance numeric(10,4),
        max_supply numeric(30,4),
        percent_change1h numeric(10,4),
        percent_change24h numeric(10,4),
        percent_change7d numeric(10,4),
        total_supply numeric(30,4),
        volume24h numeric(30,2),
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        currency varchar(10) not null,
        symbol varchar(20) not null,
        name varchar(80) not null,
        slug varchar(80),
        primary key (id)
    );

    create table crypto_snapshots (
        current_price numeric(30,10) not null,
        market_cap numeric(30,2),
        price_change24h numeric(10,4),
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        currency varchar(10) not null,
        symbol varchar(20) not null,
        coin_id varchar(60) not null,
        name varchar(80) not null,
        image_url TEXT,
        primary key (id)
    );

    create table financial_data_points (
        reference_date date not null,
        secondary_value numeric(19,8),
        value numeric(19,8) not null,
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        series_id bigint not null,
        primary key (id),
        constraint uq_fdp_series_date unique (series_id, reference_date)
    );

    create table financial_series (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        source varchar(30) not null,
        unit varchar(30),
        code varchar(50) not null,
        name varchar(120) not null,
        description TEXT,
        primary key (id),
        constraint uq_series_code_source unique (code, source)
    );

    create table ibge_cities (
        id integer not null,
        state_id integer not null,
        synced_at timestamp(6) not null,
        nome varchar(100) not null,
        primary key (id)
    );

    create table ibge_states (
        id integer not null,
        regiao_id integer not null,
        regiao_sigla varchar(2) not null,
        sigla varchar(2) not null unique,
        synced_at timestamp(6) not null,
        regiao_nome varchar(20) not null,
        nome varchar(60) not null,
        primary key (id)
    );

    create table lbma_fixings (
        gold_am numeric(19,6),
        gold_pm numeric(19,6),
        palladium_am numeric(19,6),
        palladium_pm numeric(19,6),
        platinum_am numeric(19,6),
        platinum_pm numeric(19,6),
        silver numeric(19,6),
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        reference_ts timestamp(6) with time zone not null unique,
        currency varchar(10),
        primary key (id)
    );

    create table metal_history (
        aluminum numeric(19,6),
        copper numeric(19,6),
        gold numeric(19,6),
        nickel numeric(19,6),
        palladium numeric(19,6),
        platinum numeric(19,6),
        price_date date not null unique,
        silver numeric(19,6),
        zinc numeric(19,6),
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        currency varchar(10),
        unit varchar(10),
        primary key (id)
    );

    create table metal_snapshots (
        aluminum numeric(19,6),
        copper numeric(19,6),
        gold numeric(19,6),
        nickel numeric(19,6),
        palladium numeric(19,6),
        platinum numeric(19,6),
        silver numeric(19,6),
        zinc numeric(19,6),
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        reference_ts timestamp(6) with time zone not null unique,
        currency varchar(10),
        primary key (id)
    );

    create table pib_estadual_snapshots (
        uf_code integer not null,
        value numeric(23,2) not null,
        year integer not null,
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        uf varchar(60) not null,
        primary key (id),
        constraint uk_pib_estadual_year_uf unique (year, uf_code)
    );

    create table pib_snapshots (
        value numeric(23,2) not null,
        year integer not null unique,
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        currency varchar(10),
        primary key (id)
    );

    create table stock_snapshots (
        change numeric(19,4),
        change_percent numeric(10,4),
        high numeric(19,4),
        low numeric(19,4),
        open numeric(19,4),
        previous_close numeric(19,4),
        price numeric(19,4) not null,
        trading_day date not null,
        fetched_at timestamp(6) not null,
        id bigint generated by default as identity,
        volume bigint,
        symbol varchar(12) not null,
        primary key (id),
        constraint uq_stock_symbol_day unique (symbol, trading_day)
    );

    create table users (
        verified boolean not null,
        verification_code varchar(6),
        created_at timestamp(6) not null,
        verification_code_expires_at timestamp(6),
        id uuid not null,
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) not null check (role in ('USER','ADMIN')),
        primary key (id)
    );

    create index idx_bank_name 
       on banks (name);

    create index idx_cmc_coin_fetched 
       on cmc_crypto_snapshots (cmc_id, fetched_at);

    create index idx_cmc_symbol_fetched 
       on cmc_crypto_snapshots (symbol, fetched_at);

    create index idx_cmc_fetched 
       on cmc_crypto_snapshots (fetched_at);

    create index idx_crypto_coin_fetched 
       on crypto_snapshots (coin_id, fetched_at);

    create index idx_crypto_fetched 
       on crypto_snapshots (fetched_at);

    create index idx_fdp_series_date 
       on financial_data_points (series_id, reference_date);

    create index idx_fdp_reference_date 
       on financial_data_points (reference_date);

    create index idx_city_state 
       on ibge_cities (state_id);

    create index idx_city_nome 
       on ibge_cities (nome);

    create index idx_lbma_reference_ts 
       on lbma_fixings (reference_ts);

    create index idx_metal_history_price_date 
       on metal_history (price_date);

    create index idx_metal_reference_ts 
       on metal_snapshots (reference_ts);

    create index idx_pib_estadual_year 
       on pib_estadual_snapshots (year);

    create index idx_pib_year 
       on pib_snapshots (year);

    create index idx_stock_symbol_date 
       on stock_snapshots (symbol, trading_day);

    create index idx_stock_trading_day 
       on stock_snapshots (trading_day);

    alter table if exists financial_data_points 
       add constraint FK3x9lrtcfvekg8ngaq08jved92 
       foreign key (series_id) 
       references financial_series;

    alter table if exists ibge_cities 
       add constraint FK2d2rvexbdp0nynvfdffskcn8h 
       foreign key (state_id) 
       references ibge_states;
