-- V3 — Perfil profissional e acadêmico do usuário.
--
-- Substitui o antigo onboarding de endereço + dados bancários. Cria a taxonomia
-- de referência (área → subárea, compartilhada entre profissão e educação; e os
-- níveis, separados) e a tabela 1:1 user_profiles.
--
-- A taxonomia é estática e populada aqui por INSERT — não vem de API externa
-- como banks/ibge, então não precisa de seeder no startup. Para ampliar a
-- lista, crie uma V4__ com novos INSERTs.


-- ── Tabelas de referência ────────────────────────────────────────────────────

create table knowledge_areas (
    id         bigint generated by default as identity,
    slug       varchar(60) not null unique,
    name       varchar(80) not null,
    sort_order integer     not null,
    primary key (id)
);

create table knowledge_subareas (
    id         bigint generated by default as identity,
    area_id    bigint      not null,
    slug       varchar(80) not null unique,
    name       varchar(100) not null,
    sort_order integer     not null,
    primary key (id),
    constraint fk_subarea_area foreign key (area_id) references knowledge_areas (id)
);

create index idx_subarea_area on knowledge_subareas (area_id);

create table education_levels (
    id   bigint generated by default as identity,
    slug varchar(60) not null unique,
    name varchar(80) not null,
    rank integer     not null,
    primary key (id)
);

create table profession_levels (
    id   bigint generated by default as identity,
    slug varchar(60) not null unique,
    name varchar(80) not null,
    rank integer     not null,
    primary key (id)
);


-- ── Perfil do usuário (1:1 com users) ────────────────────────────────────────

create table user_profiles (
    id                    uuid not null,
    user_id               uuid not null,
    profession_area_id    bigint,
    profession_subarea_id bigint,
    profession_level_id   bigint,
    profession_title      varchar(120),
    education_area_id      bigint,
    education_subarea_id   bigint,
    education_level_id     bigint,
    institution           varchar(120),
    updated_at            timestamp(6) not null,
    primary key (id),
    constraint uk_user_profile_user unique (user_id),
    constraint fk_profile_user
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_profile_prof_area
        foreign key (profession_area_id) references knowledge_areas (id) on delete set null,
    constraint fk_profile_prof_subarea
        foreign key (profession_subarea_id) references knowledge_subareas (id) on delete set null,
    constraint fk_profile_prof_level
        foreign key (profession_level_id) references profession_levels (id) on delete set null,
    constraint fk_profile_edu_area
        foreign key (education_area_id) references knowledge_areas (id) on delete set null,
    constraint fk_profile_edu_subarea
        foreign key (education_subarea_id) references knowledge_subareas (id) on delete set null,
    constraint fk_profile_edu_level
        foreign key (education_level_id) references education_levels (id) on delete set null
);


-- ── Seed: áreas ──────────────────────────────────────────────────────────────

insert into knowledge_areas (slug, name, sort_order) values
    ('tecnologia',            'Tecnologia',              1),
    ('engenharia',            'Engenharia',              2),
    ('ciencias',              'Ciências',                3),
    ('saude',                 'Saúde',                   4),
    ('financas-economia',     'Finanças e Economia',     5),
    ('administracao-negocios','Administração e Negócios',6),
    ('direito',               'Direito',                 7),
    ('educacao',              'Educação',                8),
    ('marketing-comunicacao', 'Marketing e Comunicação', 9),
    ('industria-producao',    'Indústria e Produção',   10),
    ('comercio-servicos',     'Comércio e Serviços',    11),
    ('setor-publico',         'Setor Público',          12),
    ('agronegocio',           'Agronegócio',            13),
    ('artes-cultura',         'Artes e Cultura',        14),
    ('outra',                 'Outra',                  99);


-- ── Seed: subáreas (slug prefixado pela área garante unicidade global) ───────

insert into knowledge_subareas (area_id, slug, name, sort_order) values
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-desenvolvimento-software', 'Desenvolvimento de Software', 1),
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-dados-ia',                 'Dados e IA',                 2),
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-infraestrutura-redes',     'Infraestrutura e Redes',     3),
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-seguranca-informacao',     'Segurança da Informação',    4),
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-design-ux',                'Design e UX',                5),
    ((select id from knowledge_areas where slug='tecnologia'), 'tecnologia-suporte-tecnico',          'Suporte Técnico',            6),

    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-civil',                    'Engenharia Civil',           1),
    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-mecanica',                 'Engenharia Mecânica',        2),
    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-eletrica',                 'Engenharia Elétrica e Eletrônica', 3),
    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-producao',                 'Engenharia de Produção',     4),
    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-quimica',                  'Engenharia Química',         5),
    ((select id from knowledge_areas where slug='engenharia'), 'engenharia-ambiental',                'Engenharia Ambiental',       6),

    ((select id from knowledge_areas where slug='ciencias'),   'ciencias-biologia',                   'Biologia',                   1),
    ((select id from knowledge_areas where slug='ciencias'),   'ciencias-fisica',                     'Física',                     2),
    ((select id from knowledge_areas where slug='ciencias'),   'ciencias-quimica',                    'Química',                    3),
    ((select id from knowledge_areas where slug='ciencias'),   'ciencias-matematica-estatistica',     'Matemática e Estatística',   4),
    ((select id from knowledge_areas where slug='ciencias'),   'ciencias-geociencias',                'Geociências',                5),

    ((select id from knowledge_areas where slug='saude'),      'saude-medicina',                      'Medicina',                   1),
    ((select id from knowledge_areas where slug='saude'),      'saude-enfermagem',                    'Enfermagem',                 2),
    ((select id from knowledge_areas where slug='saude'),      'saude-farmacia',                      'Farmácia',                   3),
    ((select id from knowledge_areas where slug='saude'),      'saude-odontologia',                   'Odontologia',                4),
    ((select id from knowledge_areas where slug='saude'),      'saude-psicologia',                    'Psicologia',                 5),
    ((select id from knowledge_areas where slug='saude'),      'saude-nutricao',                      'Nutrição',                   6),
    ((select id from knowledge_areas where slug='saude'),      'saude-fisioterapia',                  'Fisioterapia',               7),

    ((select id from knowledge_areas where slug='financas-economia'), 'financas-contabilidade',        'Contabilidade',              1),
    ((select id from knowledge_areas where slug='financas-economia'), 'financas-corporativas',         'Finanças Corporativas',      2),
    ((select id from knowledge_areas where slug='financas-economia'), 'financas-economia',             'Economia',                   3),
    ((select id from knowledge_areas where slug='financas-economia'), 'financas-investimentos',        'Investimentos',              4),
    ((select id from knowledge_areas where slug='financas-economia'), 'financas-auditoria',            'Auditoria',                  5),

    ((select id from knowledge_areas where slug='administracao-negocios'), 'admin-gestao-estrategia',   'Gestão e Estratégia',        1),
    ((select id from knowledge_areas where slug='administracao-negocios'), 'admin-recursos-humanos',    'Recursos Humanos',           2),
    ((select id from knowledge_areas where slug='administracao-negocios'), 'admin-vendas',              'Vendas',                     3),
    ((select id from knowledge_areas where slug='administracao-negocios'), 'admin-logistica-operacoes', 'Logística e Operações',      4),
    ((select id from knowledge_areas where slug='administracao-negocios'), 'admin-empreendedorismo',    'Empreendedorismo',           5),

    ((select id from knowledge_areas where slug='direito'),    'direito-advocacia',                   'Advocacia',                  1),
    ((select id from knowledge_areas where slug='direito'),    'direito-publico',                     'Direito Público',            2),
    ((select id from knowledge_areas where slug='direito'),    'direito-empresarial',                 'Direito Empresarial',        3),
    ((select id from knowledge_areas where slug='direito'),    'direito-compliance',                  'Compliance',                 4),

    ((select id from knowledge_areas where slug='educacao'),   'educacao-docencia',                   'Docência',                   1),
    ((select id from knowledge_areas where slug='educacao'),   'educacao-pesquisa-academica',         'Pesquisa Acadêmica',         2),
    ((select id from knowledge_areas where slug='educacao'),   'educacao-gestao-escolar',             'Gestão Escolar',             3),
    ((select id from knowledge_areas where slug='educacao'),   'educacao-pedagogia',                  'Pedagogia',                  4),

    ((select id from knowledge_areas where slug='marketing-comunicacao'), 'mkt-marketing-digital',     'Marketing Digital',          1),
    ((select id from knowledge_areas where slug='marketing-comunicacao'), 'mkt-publicidade',           'Publicidade e Propaganda',   2),
    ((select id from knowledge_areas where slug='marketing-comunicacao'), 'mkt-jornalismo',            'Jornalismo',                 3),
    ((select id from knowledge_areas where slug='marketing-comunicacao'), 'mkt-design-grafico',        'Design Gráfico',             4),
    ((select id from knowledge_areas where slug='marketing-comunicacao'), 'mkt-relacoes-publicas',     'Relações Públicas',          5),

    ((select id from knowledge_areas where slug='industria-producao'), 'industria-manufatura',         'Manufatura',                 1),
    ((select id from knowledge_areas where slug='industria-producao'), 'industria-controle-qualidade', 'Controle de Qualidade',      2),
    ((select id from knowledge_areas where slug='industria-producao'), 'industria-manutencao',         'Manutenção Industrial',      3),
    ((select id from knowledge_areas where slug='industria-producao'), 'industria-planejamento',       'Planejamento de Produção',   4),

    ((select id from knowledge_areas where slug='comercio-servicos'), 'comercio-varejo',               'Varejo',                     1),
    ((select id from knowledge_areas where slug='comercio-servicos'), 'comercio-atendimento',          'Atendimento ao Cliente',     2),
    ((select id from knowledge_areas where slug='comercio-servicos'), 'comercio-turismo-hospitalidade','Turismo e Hospitalidade',    3),
    ((select id from knowledge_areas where slug='comercio-servicos'), 'comercio-alimentacao',          'Alimentação e Gastronomia',  4),

    ((select id from knowledge_areas where slug='setor-publico'), 'publico-administracao',             'Administração Pública',      1),
    ((select id from knowledge_areas where slug='setor-publico'), 'publico-seguranca',                 'Segurança Pública',          2),
    ((select id from knowledge_areas where slug='setor-publico'), 'publico-politicas',                 'Políticas Públicas',         3),
    ((select id from knowledge_areas where slug='setor-publico'), 'publico-diplomacia',                'Diplomacia',                 4),

    ((select id from knowledge_areas where slug='agronegocio'), 'agro-agronomia',                      'Agronomia',                  1),
    ((select id from knowledge_areas where slug='agronegocio'), 'agro-veterinaria',                    'Medicina Veterinária',       2),
    ((select id from knowledge_areas where slug='agronegocio'), 'agro-zootecnia',                      'Zootecnia',                  3),
    ((select id from knowledge_areas where slug='agronegocio'), 'agro-gestao-rural',                   'Gestão Rural',               4),

    ((select id from knowledge_areas where slug='artes-cultura'), 'artes-visuais',                     'Artes Visuais',              1),
    ((select id from knowledge_areas where slug='artes-cultura'), 'artes-musica',                      'Música',                     2),
    ((select id from knowledge_areas where slug='artes-cultura'), 'artes-audiovisual',                 'Audiovisual e Cinema',       3),
    ((select id from knowledge_areas where slug='artes-cultura'), 'artes-literatura',                  'Literatura',                 4),
    ((select id from knowledge_areas where slug='artes-cultura'), 'artes-cenicas',                     'Artes Cênicas',              5),

    ((select id from knowledge_areas where slug='outra'),      'outra-outra',                         'Outra',                      1);


-- ── Seed: níveis de educação ─────────────────────────────────────────────────

insert into education_levels (slug, name, rank) values
    ('fundamental',        'Ensino Fundamental',              1),
    ('medio',              'Ensino Médio',                    2),
    ('tecnico',            'Ensino Técnico',                  3),
    ('tecnologo',          'Tecnólogo',                       4),
    ('graduacao-cursando', 'Graduação (cursando)',            5),
    ('graduacao',          'Graduação (completa)',            6),
    ('pos-graduacao',      'Pós-graduação / Especialização',  7),
    ('mestrado',           'Mestrado',                        8),
    ('doutorado',          'Doutorado',                       9),
    ('pos-doutorado',      'Pós-doutorado',                  10);


-- ── Seed: níveis de profissão ────────────────────────────────────────────────

insert into profession_levels (slug, name, rank) values
    ('estagiario',   'Estagiário',              1),
    ('trainee',      'Trainee',                 2),
    ('junior',       'Júnior',                  3),
    ('pleno',        'Pleno',                   4),
    ('senior',       'Sênior',                  5),
    ('especialista', 'Especialista',            6),
    ('coordenacao',  'Coordenação',             7),
    ('gerencia',     'Gerência',                8),
    ('diretoria',    'Diretoria / Executivo',   9),
    ('autonomo',     'Autônomo / Freelancer',  10),
    ('empresario',   'Empresário / Sócio',     11),
    ('estudante',    'Estudante / Ainda não atuo', 12);
