export const CURRENCIES = [
  { code: 'USD', name: 'Dólar Americano', flag: '🇺🇸' },
  { code: 'AED', name: 'Dirham dos Emirados', flag: '🇦🇪' },
  { code: 'AFN', name: 'Afghani Afegão', flag: '🇦🇫' },
  { code: 'ALL', name: 'Lek Albanês', flag: '🇦🇱' },
  { code: 'AMD', name: 'Dram Armênio', flag: '🇦🇲' },
  { code: 'ANG', name: 'Florim Antilhano', flag: '🇨🇼' },
  { code: 'AOA', name: 'Kwanza Angolano', flag: '🇦🇴' },
  { code: 'ARS', name: 'Peso Argentino', flag: '🇦🇷' },
  { code: 'AUD', name: 'Dólar Australiano', flag: '🇦🇺' },
  { code: 'AWG', name: 'Florim Arubano', flag: '🇦🇼' },
  { code: 'AZN', name: 'Manat Azerbaijano', flag: '🇦🇿' },
  { code: 'BAM', name: 'Marco Conversível da Bósnia', flag: '🇧🇦' },
  { code: 'BBD', name: 'Dólar de Barbados', flag: '🇧🇧' },
  { code: 'BDT', name: 'Taka de Bangladesh', flag: '🇧🇩' },
  { code: 'BGN', name: 'Lev Búlgaro', flag: '🇧🇬' },
  { code: 'BHD', name: 'Dinar do Bahrein', flag: '🇧🇭' },
  { code: 'BIF', name: 'Franco Burundiano', flag: '🇧🇮' },
  { code: 'BMD', name: 'Dólar das Bermudas', flag: '🇧🇲' },
  { code: 'BND', name: 'Dólar de Brunei', flag: '🇧🇳' },
  { code: 'BOB', name: 'Boliviano', flag: '🇧🇴' },
  { code: 'BRL', name: 'Real Brasileiro', flag: '🇧🇷' },
  { code: 'BSD', name: 'Dólar das Bahamas', flag: '🇧🇸' },
  { code: 'BTN', name: 'Ngultrum do Butão', flag: '🇧🇹' },
  { code: 'BWP', name: 'Pula de Botsuana', flag: '🇧🇼' },
  { code: 'BYN', name: 'Rublo Bielorrusso', flag: '🇧🇾' },
  { code: 'BZD', name: 'Dólar de Belize', flag: '🇧🇿' },
  { code: 'CAD', name: 'Dólar Canadense', flag: '🇨🇦' },
  { code: 'CDF', name: 'Franco Congolês', flag: '🇨🇩' },
  { code: 'CHF', name: 'Franco Suíço', flag: '🇨🇭' },
  { code: 'CLF', name: 'Unidade de Fomento (Chile)', flag: '🇨🇱' },
  { code: 'CLP', name: 'Peso Chileno', flag: '🇨🇱' },
  { code: 'CNH', name: 'Yuan Offshore', flag: '🇨🇳' },
  { code: 'CNY', name: 'Yuan Chinês', flag: '🇨🇳' },
  { code: 'COP', name: 'Peso Colombiano', flag: '🇨🇴' },
  { code: 'CRC', name: 'Colón Costa-Riquenho', flag: '🇨🇷' },
  { code: 'CUP', name: 'Peso Cubano', flag: '🇨🇺' },
  { code: 'CVE', name: 'Escudo Cabo-Verdiano', flag: '🇨🇻' },
  { code: 'CZK', name: 'Coroa Tcheca', flag: '🇨🇿' },
  { code: 'DJF', name: 'Franco do Djibuti', flag: '🇩🇯' },
  { code: 'DKK', name: 'Coroa Dinamarquesa', flag: '🇩🇰' },
  { code: 'DOP', name: 'Peso Dominicano', flag: '🇩🇴' },
  { code: 'DZD', name: 'Dinar Argelino', flag: '🇩🇿' },
  { code: 'EGP', name: 'Libra Egípcia', flag: '🇪🇬' },
  { code: 'ERN', name: 'Nakfa Eritreia', flag: '🇪🇷' },
  { code: 'ETB', name: 'Birr Etíope', flag: '🇪🇹' },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺' },
  { code: 'FJD', name: 'Dólar Fijiano', flag: '🇫🇯' },
  { code: 'FKP', name: 'Libra das Malvinas', flag: '🇫🇰' },
  { code: 'FOK', name: 'Coroa Feroesa', flag: '🇫🇴' },
  { code: 'GBP', name: 'Libra Esterlina', flag: '🇬🇧' },
  { code: 'GEL', name: 'Lari Georgiano', flag: '🇬🇪' },
  { code: 'GGP', name: 'Libra de Guernsey', flag: '🇬🇬' },
  { code: 'GHS', name: 'Cedi Ganês', flag: '🇬🇭' },
  { code: 'GIP', name: 'Libra de Gibraltar', flag: '🇬🇮' },
  { code: 'GMD', name: 'Dalasi da Gâmbia', flag: '🇬🇲' },
  { code: 'GNF', name: 'Franco Guineense', flag: '🇬🇳' },
  { code: 'GTQ', name: 'Quetzal Guatemalteco', flag: '🇬🇹' },
  { code: 'GYD', name: 'Dólar da Guiana', flag: '🇬🇾' },
  { code: 'HKD', name: 'Dólar de Hong Kong', flag: '🇭🇰' },
  { code: 'HNL', name: 'Lempira Hondurenha', flag: '🇭🇳' },
  { code: 'HRK', name: 'Kuna Croata', flag: '🇭🇷' },
  { code: 'HTG', name: 'Gourde Haitiano', flag: '🇭🇹' },
  { code: 'HUF', name: 'Florim Húngaro', flag: '🇭🇺' },
  { code: 'IDR', name: 'Rupia Indonésia', flag: '🇮🇩' },
  { code: 'ILS', name: 'Novo Shekel Israelense', flag: '🇮🇱' },
  { code: 'IMP', name: 'Libra Manesa', flag: '🇮🇲' },
  { code: 'INR', name: 'Rupia Indiana', flag: '🇮🇳' },
  { code: 'IQD', name: 'Dinar Iraquiano', flag: '🇮🇶' },
  { code: 'IRR', name: 'Rial Iraniano', flag: '🇮🇷' },
  { code: 'ISK', name: 'Coroa Islandesa', flag: '🇮🇸' },
  { code: 'JEP', name: 'Libra de Jersey', flag: '🇯🇪' },
  { code: 'JMD', name: 'Dólar Jamaicano', flag: '🇯🇲' },
  { code: 'JOD', name: 'Dinar Jordaniano', flag: '🇯🇴' },
  { code: 'JPY', name: 'Iene Japonês', flag: '🇯🇵' },
  { code: 'KES', name: 'Xelim Queniano', flag: '🇰🇪' },
  { code: 'KGS', name: 'Som Quirguiz', flag: '🇰🇬' },
  { code: 'KHR', name: 'Riel Cambojano', flag: '🇰🇭' },
  { code: 'KID', name: 'Dólar de Kiribati', flag: '🇰🇮' },
  { code: 'KMF', name: 'Franco Comoriano', flag: '🇰🇲' },
  { code: 'KRW', name: 'Won Sul-Coreano', flag: '🇰🇷' },
  { code: 'KWD', name: 'Dinar Kuwaitiano', flag: '🇰🇼' },
  { code: 'KYD', name: 'Dólar das Ilhas Cayman', flag: '🇰🇾' },
  { code: 'KZT', name: 'Tenge Cazaque', flag: '🇰🇿' },
  { code: 'LAK', name: 'Kip Laosiano', flag: '🇱🇦' },
  { code: 'LBP', name: 'Libra Libanesa', flag: '🇱🇧' },
  { code: 'LKR', name: 'Rupia do Sri Lanka', flag: '🇱🇰' },
  { code: 'LRD', name: 'Dólar Liberiano', flag: '🇱🇷' },
  { code: 'LSL', name: 'Loti do Lesoto', flag: '🇱🇸' },
  { code: 'LYD', name: 'Dinar Líbio', flag: '🇱🇾' },
  { code: 'MAD', name: 'Dirham Marroquino', flag: '🇲🇦' },
  { code: 'MDL', name: 'Leu Moldavo', flag: '🇲🇩' },
  { code: 'MGA', name: 'Ariary Malgaxe', flag: '🇲🇬' },
  { code: 'MKD', name: 'Denar Macedônio', flag: '🇲🇰' },
  { code: 'MMK', name: 'Kyat de Mianmar', flag: '🇲🇲' },
  { code: 'MNT', name: 'Tugrik Mongol', flag: '🇲🇳' },
  { code: 'MOP', name: 'Pataca de Macau', flag: '🇲🇴' },
  { code: 'MRU', name: 'Ouguiya Mauritana', flag: '🇲🇷' },
  { code: 'MUR', name: 'Rupia Mauriciana', flag: '🇲🇺' },
  { code: 'MVR', name: 'Rupia Maldiva', flag: '🇲🇻' },
  { code: 'MWK', name: 'Kwacha Malauiana', flag: '🇲🇼' },
  { code: 'MXN', name: 'Peso Mexicano', flag: '🇲🇽' },
  { code: 'MYR', name: 'Ringgit Malaio', flag: '🇲🇾' },
  { code: 'MZN', name: 'Metical Moçambicano', flag: '🇲🇿' },
  { code: 'NAD', name: 'Dólar Namibiano', flag: '🇳🇦' },
  { code: 'NGN', name: 'Naira Nigeriana', flag: '🇳🇬' },
  { code: 'NIO', name: 'Córdoba Nicaraguense', flag: '🇳🇮' },
  { code: 'NOK', name: 'Coroa Norueguesa', flag: '🇳🇴' },
  { code: 'NPR', name: 'Rupia Nepalesa', flag: '🇳🇵' },
  { code: 'NZD', name: 'Dólar Neozelandês', flag: '🇳🇿' },
  { code: 'OMR', name: 'Rial Omanense', flag: '🇴🇲' },
  { code: 'PAB', name: 'Balboa Panamenho', flag: '🇵🇦' },
  { code: 'PEN', name: 'Sol Peruano', flag: '🇵🇪' },
  { code: 'PGK', name: 'Kina Papua-Nova Guiné', flag: '🇵🇬' },
  { code: 'PHP', name: 'Peso Filipino', flag: '🇵🇭' },
  { code: 'PKR', name: 'Rupia Paquistanesa', flag: '🇵🇰' },
  { code: 'PLN', name: 'Zloty Polonês', flag: '🇵🇱' },
  { code: 'PYG', name: 'Guarani Paraguaio', flag: '🇵🇾' },
  { code: 'QAR', name: 'Rial Catarense', flag: '🇶🇦' },
  { code: 'RON', name: 'Leu Romeno', flag: '🇷🇴' },
  { code: 'RSD', name: 'Dinar Sérvio', flag: '🇷🇸' },
  { code: 'RUB', name: 'Rublo Russo', flag: '🇷🇺' },
  { code: 'RWF', name: 'Franco Ruandês', flag: '🇷🇼' },
  { code: 'SAR', name: 'Rial Saudita', flag: '🇸🇦' },
  { code: 'SBD', name: 'Dólar das Ilhas Salomão', flag: '🇸🇧' },
  { code: 'SCR', name: 'Rupia de Seychelles', flag: '🇸🇨' },
  { code: 'SDG', name: 'Libra Sudanesa', flag: '🇸🇩' },
  { code: 'SEK', name: 'Coroa Sueca', flag: '🇸🇪' },
  { code: 'SGD', name: 'Dólar de Singapura', flag: '🇸🇬' },
  { code: 'SHP', name: 'Libra de Santa Helena', flag: '🇸🇭' },
  { code: 'SLE', name: 'Leone de Serra Leoa', flag: '🇸🇱' },
  { code: 'SLL', name: 'Leone Antigo de Serra Leoa', flag: '🇸🇱' },
  { code: 'SOS', name: 'Xelim Somali', flag: '🇸🇴' },
  { code: 'SRD', name: 'Dólar do Suriname', flag: '🇸🇷' },
  { code: 'SSP', name: 'Libra Sul-Sudanesa', flag: '🇸🇸' },
  { code: 'STN', name: 'Dobra São-Tomense', flag: '🇸🇹' },
  { code: 'SYP', name: 'Libra Síria', flag: '🇸🇾' },
  { code: 'SZL', name: 'Lilangeni Suazi', flag: '🇸🇿' },
  { code: 'THB', name: 'Baht Tailandês', flag: '🇹🇭' },
  { code: 'TJS', name: 'Somoni Tadjique', flag: '🇹🇯' },
  { code: 'TMT', name: 'Manat Turcomeno', flag: '🇹🇲' },
  { code: 'TND', name: 'Dinar Tunisiano', flag: '🇹🇳' },
  { code: 'TOP', name: 'Paʻanga Tonganesa', flag: '🇹🇴' },
  { code: 'TRY', name: 'Lira Turca', flag: '🇹🇷' },
  { code: 'TTD', name: 'Dólar de Trinidad e Tobago', flag: '🇹🇹' },
  { code: 'TVD', name: 'Dólar Tuvaluano', flag: '🇹🇻' },
  { code: 'TWD', name: 'Novo Dólar Taiwanês', flag: '🇹🇼' },
  { code: 'TZS', name: 'Xelim Tanzaniano', flag: '🇹🇿' },
  { code: 'UAH', name: 'Hryvnia Ucraniana', flag: '🇺🇦' },
  { code: 'UGX', name: 'Xelim Ugandense', flag: '🇺🇬' },
  { code: 'UYU', name: 'Peso Uruguaio', flag: '🇺🇾' },
  { code: 'UZS', name: 'Som Uzbeque', flag: '🇺🇿' },
  { code: 'VES', name: 'Bolívar Venezuelano', flag: '🇻🇪' },
  { code: 'VND', name: 'Dong Vietnamita', flag: '🇻🇳' },
  { code: 'VUV', name: 'Vatu de Vanuatu', flag: '🇻🇺' },
  { code: 'WST', name: 'Tala Samoana', flag: '🇼🇸' },
  { code: 'XAF', name: 'Franco CFA Central', flag: '🌍' },
  { code: 'XCD', name: 'Dólar do Caribe Oriental', flag: '🌎' },
  { code: 'XCG', name: 'Franco CFA (genérico)', flag: '🌍' },
  { code: 'XDR', name: 'Direitos Especiais de Saque (FMI)', flag: '🏦' },
  { code: 'XOF', name: 'Franco CFA Ocidental', flag: '🌍' },
  { code: 'XPF', name: 'Franco CFP (Pacífico)', flag: '🌏' },
  { code: 'YER', name: 'Rial Iemenita', flag: '🇾🇪' },
  { code: 'ZAR', name: 'Rand Sul-Africano', flag: '🇿🇦' },
  { code: 'ZMW', name: 'Kwacha Zambiana', flag: '🇿🇲' },
  { code: 'ZWG', name: 'Dólar de Ouro do Zimbábue', flag: '🇿🇼' },
  { code: 'ZWL', name: 'Dólar do Zimbábue', flag: '🇿🇼' },
] as const;

export type CurrencyCode = typeof CURRENCIES[number]['code'];
